### ISSUE TITLE
Add way to set background color

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-2d-drawing#9]
Since the user might want to use a gradient fill or something more complicated than a solid color, it might make sense to treat the background as a rectangle that exactly matches the viewBox size.

**Comment by ianmackenzie** [comment]
Maybe something like

```elm
module Drawing2d

type Background drawingUnits drawingCoordinates

noBackground : Background drawingUnits drawingCoordinates
blackBackground : Background drawingUnits drawingCoordinates
whiteBackground : Background drawingUnits drawingCoordinates
backgroundColor : Color -> Background drawingUnits drawingCoordinates
backgroundGradient : Gradient units coordinates -> Background drawingUnits drawingCoordinates
```

and then pass something like

```elm
{ viewBox = viewBox
, background = Drawing2d.backgroundColor color
}
```

when rendering?

The various `Background` constructors would map 1:1 with the various fill attributes and would simply apply the corresponding fill attribute to a background rectangle. It could be slightly simpler to just pass an `Attribute` instead of a `Background`, but then it would be possible to pass nonsensical things like `background = Drawing2d.roundStrokeJoins`.

**Comment by MartinSStewart** [comment]
Yeah, I think this approach makes sense.
